# Generated by Django 3.1.2 on 2020-10-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
